################### Beat Configuration #########################
traceability_agent:
  inputs:
    - type: log
      paths: ${EVENT_LOG_PATHS:/Users/rnatarajan/go/src/github.com/rathnapandi/spring-traceability-agent/log.json}
      #include_lines: ['.*"type":"transaction".*"type":"http".*']
#      ignore_older: 1h
#      close_inactive: 10m
#      clean_inactive: 2h
#      close_removed: true
#      clean_removed: true
  # Settings for connecting to AMPLIFY Central
  central:
    url: ${CENTRAL_URL:https://apicentral.axway.com}
    organizationID: ${CENTRAL_ORGANIZATIONID:""}
    team: ${CENTRAL_TEAM:""}
    deployment: ${CENTRAL_DEPLOYMENT:prod}
    environment: ${CENTRAL_ENVIRONMENT:""}
    agentName: ${CENTRAL_AGENTNAME:""}
    platformURL: ${CENTRAL_PLATFORMURL:https://platform.axway.com}
    auth:
      url: ${CENTRAL_AUTH_URL:https://login.axway.com/auth}
      realm: ${CENTRAL_AUTH_REALM:Broker}
      clientId: ${CENTRAL_AUTH_CLIENTID:""}
      privateKey: ${CENTRAL_AUTH_PRIVATEKEY:./private_key.pem}
      publicKey: ${CENTRAL_AUTH_PUBLICKEY:./public_key.pem}
      keyPassword: ${CENTRAL_AUTH_KEYPASSWORD:""}
      timeout: 10s
    ssl:
      minVersion: ${CENTRAL_SSL_MINVERSION:""}
      maxVersion: ${CENTRAL_SSL_MAXVERSION:""}
      nextProtos: ${CENTRAL_SSL_NEXTPROTOS:[]}
      cipherSuites: ${CENTRAL_SSL_CIPHERSUITES:[]}
      insecureSkipVerify: ${CENTRAL_SSL_INSECURESKIPVERIFY:false}
    proxyUrl: ${CENTRAL_PROXYURL:""}

  status:
    port: ${STATUS_PORT:8990}
    healthCheckPeriod: ${STATUS_HEALTHCHECKPERIOD:3m}
    healthCheckInterval: ${STATUS_HEALTHCHECKINTERVAL:30s}

# Send output to Central Database
output.traceability:
  enabled: true
  hosts: ${TRACEABILITY_HOST:ingestion-lumberjack.datasearch.axway.com:453}
  protocol: ${TRACEABILITY_PROTOCOL:"tcp"}
  compression_level: ${TRACEABILITY_COMPRESSIONLEVEL:3}
  bulk_max_size: ${TRACEABILITY_BULKMAXSIZE:100}
  timeout: ${TRACEABILITY_TIMEOUT:300s}
  pipelining: 0
  ssl:
    enabled: true
    verification_mode: none
    cipher_suites:
      - "ECDHE-ECDSA-AES-128-GCM-SHA256"
      - "ECDHE-ECDSA-AES-256-GCM-SHA384"
      - "ECDHE-ECDSA-AES-128-CBC-SHA256"
      - "ECDHE-ECDSA-CHACHA20-POLY1305"
      - "ECDHE-RSA-AES-128-CBC-SHA256"
      - "ECDHE-RSA-AES-128-GCM-SHA256"
      - "ECDHE-RSA-AES-256-GCM-SHA384"
  proxy_url: ${TRACEABILITY_PROXYURL:""}

queue:
  mem:
    events: ${QUEUE_MEM_EVENTS:2048}
    flush:
      min_events: ${QUEUE_MEM_FLUSH_MINEVENTS:100}
      timeout: ${QUEUE_MEM_FLUSH_TIMEOUT:1s}

logging:
  metrics:
    enabled: false
  # Send all logging output to stderr
  to_stderr: true
  # Set log level
  level: ${LOG_LEVEL:info}
